### ISSUE TITLE
Add a default path to save files

### ISSUE THREAD

**Issue by MarcAnt01** [MarcAnt01/Fluent-Screen-Recorder#1]
The user can choose a default path to save files, otherwise the filesavepicker will pop up, letting him choose the location and the filename

**Comment by FireCubeStudios** [comment]
detail please

**Comment by MarcAnt01** [comment]
That's the stuff about choosing default path I am already working on, edited the issue to be clearer

**Comment by MarcAnt01** [comment]
I am closing it, since https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/11 makes more sense
