### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by MarcAnt01** [MarcAnt01/Fluent-Screen-Recorder#10]

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Could you assign me on this issue?

**Comment by MarcAnt01** [comment]
Done👍

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 I tried 2.0 and it only has internal audio and not external audio

**Comment by MarcAnt01** [comment]
Internal audio will come at a later stage

**Comment by Jaiganeshkumaran** [comment]
Also, why is there no source code for the component? I want to contribute

**Comment by MarcAnt01** [comment]
The component uses wasapi to record internal audio and I decided to keep the source private for the moment. If you want to work on external audio you won't need it
