### ISSUE TITLE
[Contributions] Complete redesign of the application

### ISSUE THREAD

**Issue by steam3d** [MarcAnt01/Fluent-Screen-Recorder#100]
I can create a new design for the application. I can even try to implement it. (But i'm not particularly good at programming)
will it be included in the application?

**Comment by itsWindows11** [comment]
There's already one in #87, but feel free to create your own concept.

**Comment by MarcAnt01** [comment]
Yeah, as @itsWindows11 said, that's already being worked on, feel free to read the thread and provide suggestions :)
