### ISSUE TITLE
Microphone recording option is disabled

### ISSUE THREAD

**Issue by kolappannathan** [MarcAnt01/Fluent-Screen-Recorder#106]
![image](https://user-images.githubusercontent.com/8157105/147807220-271242b1-8fa5-495c-b6f4-ed798ae7b65a.png)

I have given Microphone permission to the app. My system has a microphone and Windows Voice recorder detects it.

The app version is 2.1.1 and Windows version is Windows 11 Build 22000.376

**Comment by MarcAnt01** [comment]
Hello @kolappannathan if you disable internal audio recording, you should be able to select it. Sorry if this is a bit confusing, but the ux will be certainly improved in the next versions

**Comment by kolappannathan** [comment]
That was the case. Thanks.
