### ISSUE TITLE
ScreenSenderComponent.dll is not allowed.

### ISSUE THREAD

**Issue by DooneZhang** [MarcAnt01/Fluent-Screen-Recorder#112]
When loading the library file in another project, the library file ScreenSenderComponent.dll cannot be accessed and an error is displayed:
Exception thrown at 0x7752E7B2 (in xxxxxx.exe): Microsoft C++ Exception: Platform::AccessDeniedException ^ at memory location 0x0907DA44. HRESULT: 0x80070005 Access denied.
WinRT message: Package is not allowed.

What is the reason for this? I would be grateful if you could help me

**Comment by MarcAnt01** [comment]
Hello, the library is made not to be accessible by other applications. The app is open source, but the library is locked to be used only in Fluent Screen Recorder

**Comment by DooneZhang** [comment]
Well, so pity, but thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Filippo ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MarcAnt01/Fluent-Screen-Recorder] ScreenSenderComponent.dll is not allowed. (Issue #112)






您好，该库是使其他应用程序不能访问。这个应用是开源的，但是库被锁定了，只能在 Fluent Screen Recorder 中使用

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;
