### ISSUE TITLE
Add "Open file location" menu in context menu of recorded videos

### ISSUE THREAD

**Issue by binamralamsal** [MarcAnt01/Fluent-Screen-Recorder#114]
Something like this:
https://user-images.githubusercontent.com/61900781/159674346-3c4187ff-88ba-498d-a2b6-e3f4f190ef84.mp4

This is what I did: (Although I am not sure if it will work in most cases as I am not that familiar with UWP/C#)
```c#
private async void OpenFileLocation_Click(object sender, RoutedEventArgs e)
{
    var folderLocation = await KnownFolders.VideosLibrary.GetFolderAsync("Fluent Screen Recorder");
    var options = new FolderLauncherOptions();
    options.ItemsToSelect.Add(recordedVideoFile);
    await Launcher.LaunchFolderAsync(folderLocation, options);
}
```

**Comment by MarcAnt01** [comment]
@Jaiganeshkumaran suggested this and I tried this, but the sandbox prevents me to launch the uri even if i already got access to it
