### ISSUE TITLE
Slow saviging with internal audio turned on

### ISSUE THREAD

**Issue by jonshipman** [MarcAnt01/Fluent-Screen-Recorder#115]
Also a high number of page faults being seen on save. Just wondering if there's a correlation. Recorded 40 minutes of video and the "Saving" took nearly 20 minutes.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/12699954/169560437-9d880804-bfd7-44e7-9f28-15b0a6fe460a.png">

**Comment by MarcAnt01** [comment]
Hello, sorry about this issue, I usually test the app for short recordings, but I would need more information to proceed. Is audio recording enabled? I think it is what causes the issues, I'm planning to rewrite the internal recording to be real time

**Comment by jonshipman** [comment]
Yes, audio recording is enabled.

**Comment by MarcAnt01** [comment]
Hey, after some investigations the only way to have fast saving would be to have internal audio being saved to a file in real time, but this is not possible without rewriting the whole app in a new programming language, which I don't plan. I'm sorry but there's no way to work this around, if you need fast saving the only way is to disable internal audio

**Comment by jonshipman** [comment]
Thanks for looking into it. I may try for a PR then if I manage to get some free time.
