### ISSUE TITLE
Brazilian Portuguese language

### ISSUE THREAD

**Issue by maisondasilva** [MarcAnt01/Fluent-Screen-Recorder#116]
I use the app and I see that it has pt-pt portuguese de portugal which is a little different from pt-br can I translate and send a request to our language?

**Comment by MarcAnt01** [comment]
Sure, that'd be certainly welcome. You can find the instructions here https://github.com/MarcAnt01/Fluent-Screen-Recorder/blob/master/translations.md

**Comment by maisondasilva** [comment]
Thanks for the receptivity, you can close.
