### ISSUE TITLE
This app runs on Mixed Reality devices as well (not HoloLens)

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [MarcAnt01/Fluent-Screen-Recorder#13]
Mixed reality devices that needs to connect to a PC to work not HoloLens.

**Comment by MarcAnt01** [comment]
Great to know, do these devices have particular requirements to run apps?

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 I don't own one but these devices can run all Windows apps including Win32 apps because they are connected to your PC. You can run any app on your PC in there. This is not the case with HoloLens which runs Windows.Holographic while these devices run Windows.Desktop which supports everything but they need to be connected with your PC. To be sure just run the Mixed reality simulator inside Mixed reality portal which emulates a headset. Also the documentation clearly says that it runs on these headsets: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture

**Comment by Jaiganeshkumaran** [comment]
Although Microsoft says Mixed reality, they are essentially VR headsets that projects the content from your PC. HoloLens is the real mixed reality device and it is standalone so it doesn't run your app.
