### ISSUE TITLE
Cant stop recording when recording minimized apps

### ISSUE THREAD

**Issue by FireCubeStudios** [MarcAnt01/Fluent-Screen-Recorder#18]
orginial messege: https://discord.com/channels/714581497222398064/714584060172959784/752908242580930690
screen recording randomly doesnt allow user to stop recording when recording apps

**Comment by MarcAnt01** [comment]
This should be linked to https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/9 , but am not 100% sure

**Comment by MarcAnt01** [comment]
OK, after further research this is happens in the following scenario:
- Start app recording with a window that is in background;
- instead of minimizing Fluent Screen Recorder window, open the app you'd like to record via taskbar;
- once you go back to the application you can't stop the recording.
