### ISSUE TITLE
less responsive 

### ISSUE THREAD

**Issue by harsha21012000** [MarcAnt01/Fluent-Screen-Recorder#19]
when i click on stop recording it takes more time to stop and isn't responsive. And also Make Ui Better appearance as it would be good to look.

**Comment by MarcAnt01** [comment]
Hi, stopping the video is instantaneous here. As for the UI, do you have any specific suggestions?

**Comment by harsha21012000** [comment]
> when i click on stop recording it takes more time to stop and isn't responsive. And also Make Ui Better appearance as it would be good to look.



> Hi, stopping the video is instantaneous here. As for the UI, do you have any specific suggestions?

though it was instantaneous but still its shows recording, I'm confused with it. Can you add features like delete, trim,Pause like so. here is the attachment i took it from windows voice recorder app.
![image](https://user-images.githubusercontent.com/41331497/92503912-8c4d3700-f21f-11ea-920f-dce159286be0.png)

and also, I have few suggestions regarding UI. Instead of using Acrylic background on the left pane use a Pleasant background 
that would make appearance good. have a look at this to make app better which i picked from to-do App.
![image](https://user-images.githubusercontent.com/41331497/92505357-95d79e80-f221-11ea-8ed9-825ee8e92ccd.png)

**Comment by MarcAnt01** [comment]
1. The app currently doesn't contain a video player, but I am already planning it but not in the far future.
2. Currently the app is meant not to be used in full screen but as a small window (like the screenshot in the Readme shows), once I add various stuff including video player the app will look good also in full screen.
3. As for the "recording" texture, it's still present in the time between the moment you press stop and when you decide to save the file or not. Anyway, I'll hide it to make it more intuitive

**Comment by MarcAnt01** [comment]
After the update in the store, it's perfect to me. Let me know if you still have problems
