### ISSUE TITLE
Add button to open saved video directory

### ISSUE THREAD

**Issue by eduherminio** [MarcAnt01/Fluent-Screen-Recorder#20]
It would be awesome to have a button to open the directory where you saved the last video using file explorer (especially if it has been saved in the default location).

PD: Congrats on the app!

**Comment by MarcAnt01** [comment]
Hi Eduardo, thanks for your suggestion. I was also suggested to automatically open the file after saving it. I was thinking about adding a combobox where you can choose if opening automatically the video file or the path where it's been saved. What are your thoughts about that?

**Comment by eduherminio** [comment]
That sounds good to me as well, would satisfy my requirements and it's probably easier to implement!

**Comment by MarcAnt01** [comment]
I could also add both, but I guess just opening the video is faster and convenient for the majority of users 😄

**Comment by eduherminio** [comment]
Feel free to close this if you're adding that 😃

**Comment by MarcAnt01** [comment]
Moreover, if you choose "Save" you'll find files in the videos library, that you can easily access with the sidebar of File Explorer
![image](https://user-images.githubusercontent.com/43090263/92893047-a05c8880-f419-11ea-8c15-bf2a511513c8.png)
