### ISSUE TITLE
New fluent design icon

### ISSUE THREAD

**Issue by akhilesh-balaji** [MarcAnt01/Fluent-Screen-Recorder#25]
Hi there!
This is, for starters, an amazing app! I have been looking for a good screen recorder with fluent design for a long time, and I finally found the best one! You may have heard that windows is updating their icons with fluent design. The current Fluent Screen Recorder icon looks rather odd in comparison with them, because it doesn't utilize gradients and shadows. I really like the concept, though. So, I designed a more fluent design-ish logo. Hope you like it!
![BeforeAfter](https://user-images.githubusercontent.com/69246693/93186554-644c5f00-f75c-11ea-951d-d4c893b0c482.png)

If you are interested, please ask me for the source files.

**Comment by MarcAnt01** [comment]
Hello, I've been already planning to change the icon and I'd like to make a new different icon. Where can I pm you?

**Comment by akhilesh-balaji** [comment]
You can pm me at akhilesh.balaji.bangalore@gmail.com

**Comment by Gavin-Williams** [comment]
I like the current icon (Before), it looks good on my taskbar.

**Comment by MarcAnt01** [comment]
This is going to be the next icon. Do you like it? @Gavin-Williams 
![image](https://user-images.githubusercontent.com/43090263/95431650-cfe5ae80-094d-11eb-940e-06aea5bd0dec.png)

**Comment by Gavin-Williams** [comment]
Yep. Simple, effective.
