### ISSUE TITLE
Videos look broken in v1.2.1.0

### ISSUE THREAD

**Issue by dpaulino** [MarcAnt01/Fluent-Screen-Recorder#26]
Here's a sample video I just recorded: https://streamable.com/jsvx7n

I checked my store and apparently an update was installed today. Yesterday I was using this app and it wasn't broken.

**Comment by dpaulino** [comment]
This is running on a Surface Laptop 3 btw

**Comment by MarcAnt01** [comment]
This looks like an encoding issue, can you tell me the bitrate, quality and framerate settings, so that I can try to reproduce? Currently all videos are encoded properly for me.

**Comment by dpaulino** [comment]
![image](https://user-images.githubusercontent.com/7649589/93908452-7aee3b00-fcb3-11ea-96c0-0fdd51dd8d2d.png)

I had the default stuff I believe. I didn't make any changes since installing the app

**Comment by dpaulino** [comment]
Hmm, I made another video just now, and it looks completely fine 🤔

**Comment by MarcAnt01** [comment]
Consider that the encoder code in 1.2.1 is identical to the one in 1.2.0 as you can see [here](https://github.com/MarcAnt01/Fluent-Screen-Recorder/blob/master/CaptureEncoder/Encoder.cs). I think it was an issue with GPU or just a problem with encoding in a specific scenario. I'll leave that open in the meanwhile I look into👍

**Comment by MarcAnt01** [comment]
@dpaulino Hi, were you able to reproduce the issue again in these months?

**Comment by dpaulino** [comment]
Nope it's been working great. Feel free to close
