### ISSUE TITLE
Code not compling

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [MarcAnt01/Fluent-Screen-Recorder#34]
In the static method save, you're trying to modify the text block's text however you can't access it since it's static which means this is empty. Please fix so that I can compile the latest changes.

**Comment by MarcAnt01** [comment]
Yep, sorry I haven't pushed the fix, will do that asap, so that you can start working on your pull request

**Comment by MarcAnt01** [comment]
@Jaiganeshkumaran you should be able to compile now
