### ISSUE TITLE
Application Crashes when I click on About this Application.

### ISSUE THREAD

**Issue by binamracode** [MarcAnt01/Fluent-Screen-Recorder#37]
![7LkXY4RiE3](https://user-images.githubusercontent.com/61900781/98565321-951cc080-22d5-11eb-8ee0-a9f544c93970.gif)

**Comment by MarcAnt01** [comment]
Thanks for reporting that, I fixed it in https://github.com/MarcAnt01/Fluent-Screen-Recorder/commit/5758cd4fc3be83c3a5994e90377ae808125c7e1e
