### ISSUE TITLE
Add support for multiple sound sources 

### ISSUE THREAD

**Issue by ahmedWaelSalem** [MarcAnt01/Fluent-Screen-Recorder#39]
Add support for different sources,
1- desktop / system sounds
2- mic sounds
and add ability to control them via sliders and ability to mute them and whatever.

**Comment by Jaiganeshkumaran** [comment]
@ahmedWaelSalem We don't even support sound it. It's being tracked in #25 10

**Comment by MarcAnt01** [comment]
Yeah, that can be an idea for once we do

**Comment by Jaiganeshkumaran** [comment]
Actually, I was planning to add an option to switch between system sound and microphone sound but if you have multiple microphones this should be a bit tricky.

**Comment by ahmedWaelSalem** [comment]
Yes, I just noticed that you still didn't add support for sounds but I think this will be good feature

**Comment by MarcAnt01** [comment]
Yeah, especially considering how uwp handles that, whatever I think having audio and mic recording is the first step, than we'll see.

**Comment by Jaiganeshkumaran** [comment]
I have gotten a device selection box working but should it retain choice after restart if the device is connected?

**Comment by MarcAnt01** [comment]
Hello, I have released Fluent Screen Record 2.0 with support for external recording trough mic. From system settings you should be easily able to pick the device you prefer
