### ISSUE TITLE
Open optionally associated folder after saving a file

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [MarcAnt01/Fluent-Screen-Recorder#45]

**Comment by MarcAnt01** [comment]
This was present in 1.3.x, but I actually removed it, since I think it makes more sense to see a preview before saving the file, why would you prefer that?

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Maybe instead of opening the file, open the folder in File Explorer instead so I don't need to go there and search

**Comment by MarcAnt01** [comment]
An option to open the directory could make sense, I usually share the files within the preview or save them in videos folder so haven't thought about that.

**Comment by MarcAnt01** [comment]
Even if I was already working on the feature ui-wise I realized that uwp sandbox is a pain in the ass and doesn't allow me to access to the folder where I save the file with the FileSavePicker.
I'm sorry but this isn't going to be considered till the app stays uwp

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 You can access the Path property of the picked file, remove the file name at the end and then call [Launcher.LaunchFolderPathAsync](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchfolderpathasync?view=winrt-20348) with [ItemsToSelect](https://docs.microsoft.com/en-us/uwp/api/windows.system.folderlauncheroptions.itemstoselect?view=winrt-20348#Windows_System_FolderLauncherOptions_ItemsToSelect) for options containing the picked file so it will be selected.

**Comment by MarcAnt01** [comment]
That's what I tried, but path keeps staying null because of the sandbox

**Comment by MarcAnt01** [comment]
`
 private static async Task<StorageFile> PickVideoAsync()
        {
            try
            {
                var picker = new FileSavePicker();
                var time = DateTime.Now.ToString("yyyy-MM-dd-HHmmss");
                picker.SuggestedStartLocation = PickerLocationId.VideosLibrary;
                picker.SuggestedFileName = $"recordedVideo{time}";
                picker.DefaultFileExtension = ".mp4";
                picker.FileTypeChoices.Add("MP4 Video", new List<string> { ".mp4" });

                StorageFile file = await picker.PickSaveFileAsync();

                string path = Path.GetDirectoryName(file.Path);
                StorageFolder pickedFolder = await StorageFolder.GetFolderFromPathAsync(path);
                if (OpenFolderOption == true)
                {
                    await Launcher.LaunchFolderAsync(pickedFolder);
                }
                return file;
            }
            catch
            {
                return null;
            }
        }
`

**Comment by MarcAnt01** [comment]
This is my snippet if you wanna take a look, but I doubt there's something wrong
![image](https://user-images.githubusercontent.com/43090263/129539843-bc580cd7-caec-45c7-8a9c-b23300ee1007.png)
