### ISSUE TITLE
Custom save folder

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [MarcAnt01/Fluent-Screen-Recorder#49]
Please add the ability to store recordings in a custom folder. In Settings, you should be able to select a folder (Videos/Fluent-Screen-Recorder should be by default) and the save button will save there next time.

**Comment by MarcAnt01** [comment]
If you select "Save as " you can pick the folder you prefer and the next time it will be automatically selected

**Comment by MarcAnt01** [comment]
"Save" saves automatically in that folder now from beta versions
