### ISSUE TITLE
Global shortcuts

### ISSUE THREAD

**Issue by MarcAnt01** [MarcAnt01/Fluent-Screen-Recorder#5]

**Comment by FireCubeStudios** [comment]
assign me to this

**Comment by FireCubeStudios** [comment]
note the global hotkeys in uwp cant work if app is closed (will work when suspended) so we will need to try a background task or another work around

**Comment by FireCubeStudios** [comment]
a system tray can be usefull too

**Comment by MarcAnt01** [comment]
Sure assigned just a few guidelines:
- I thought about ```Win+Shift+R", to make it similar to Snip&Sketch that has "Win+Shift+S";
- We can enable fulltrust without checks, since I'm planning to drop Surface Hub support;
- I don't like the idea of a tray icon, I'd rather have a settings for global shortcuts that if enabled will make the Win32 process run in background

**Comment by m98770** [comment]
> Sure assigned just a few guidelines:
> 
> * I thought about `Win+Shift+R`, to make it similar to Snip&Sketch that has `Win+Shift+S`;
> * We can enable fulltrust without checks, since I'm planning to drop Surface Hub support;
> * I don't like the idea of a tray icon, I'd rather have a settings for global shortcuts that if enabled will make the Win32 process run in background 
Please do a platform check first before launching the FullTrustProcess otherwise the app won't open at all in all the non-Desktop Platforms.

**Comment by MarcAnt01** [comment]
@m98770 the only non-Desktop platform supported by Fluent Screen Recorder is Surface Hub, but I am planning to drop it

**Comment by m98770** [comment]
@MarcAnt01 It's your choice. But, since windows 10X is happening with only PWA and UWP first, it will be the only uwp app supporting screen recording , supporting w10X makes sense to me because of the Screen Recording usecases in education sectors/students. FilesUWP trying their best to be available on windows10X ,but its completely upto you.

**Comment by MarcAnt01** [comment]
@m98770 We don't have any actual news about Windows 10X, when it's out we can reconsider things.
As for HoloLens, the original app (Simple Screen Recorder) wasn't supporting it, so I have never looked into. Anyway, their market share is very low, which doesn't worth it in my opinion. Anyway if @FireCubeStudios would like to add proper checks they're welcome  even if they'll make it harder to publish the app in the store for the future.

**Comment by FireCubeStudios** [comment]
windows 10x still has some time to come. so i dont know mcirosoft can change anything from now to then so i say its best not to worry about windows 10x for thr time being.

**Comment by MarcAnt01** [comment]
Packaging thing is done now, I still have to implement shortcuts and proper background process handling

**Comment by MarcAnt01** [comment]
I'm giving up on that, since it's too difficult, in particular handling the console app and Desktop Bridge, I am not very familiar with them. I'll leave the branch so that if anyone would like to contribute there's a starting point

**Comment by AqilCont** [comment]
Will this ever be completed? It's a bit tedious to find the app just to record something small really quick :>

**Comment by MarcAnt01** [comment]
Not soon honestly, I haven't found any way to connect the uwp and the Win32 process sadly, also using Desktop Bridge will cause store submissions that usually last from half an hour to one day to be manually certified taking up to three days. My suggestion to quickly launch the app is pin it on start, sorry

**Comment by AqilCont** [comment]
Ah, that's understandable. Thanks for replying! I'll just go with what I've been doing so far then. There's a way to bind keyboard shortcuts to shortcut files on Win10(for the others that might want this).

![image](https://user-images.githubusercontent.com/32044067/131926486-e8a76185-0695-4b92-addb-0b914e8cb740.png)

I just wanted this issue to go through so that it can provide functionalities like starting to record straightaway and can let other actions be more customizable.

**Comment by MarcAnt01** [comment]
I am closing this one, since I don't plan any longer to implement this feature in a UWP app. If in the future we'll be moving to WinUI 3, it might be implemented.
