### ISSUE TITLE
Recording freezes after some seconds

### ISSUE THREAD

**Issue by thatssotimur** [MarcAnt01/Fluent-Screen-Recorder#52]
After recording for around 5 seconds or so the recording just freezes at one point in the screen recording. Hope it gets patched soon. Keep up the great work!

**Comment by MarcAnt01** [comment]
> After recording for around 5 seconds or so the recording just freezes at one point in the screen recording. Hope it gets patched soon. Keep up the great work!

Hi, I need some more information regarding your issue. Does it happen when recording a specific app or when recording the recording. What is your app version? Would you be so kind to attach a video showing the issue? Thanks in advance

**Comment by thatssotimur** [comment]
> > After recording for around 5 seconds or so the recording just freezes at one point in the screen recording. Hope it gets patched soon. Keep up the great work!
> 
> Hi, I need some more information regarding your issue. Does it happen when recording a specific app or when recording the recording. What is your app version? Would you be so kind to attach a video showing the issue? Thanks in advance

When recording the entire screen. The app version is 1.4.5. Somehow, it's working now. But for some apps for example Microsoft Store it would fail and say that my current settings (60fps, 18 bitrate) are not supported for my hardware. And when it comes to recording a browser tab (YouTube) this happens..

Hope this helps!

https://user-images.githubusercontent.com/81487449/112732670-9cb6cc00-8f3b-11eb-8f85-19ab8366db2c.mp4

**Comment by binamracode** [comment]
Same problem but my version is 1.9.2 and this happens in both the recording app and display.

**Comment by MarcAnt01** [comment]
> > > After recording for around 5 seconds or so the recording just freezes at one point in the screen recording. Hope it gets patched soon. Keep up the great work!
> > 
> > 
> > Hi, I need some more information regarding your issue. Does it happen when recording a specific app or when recording the recording. What is your app version? Would you be so kind to attach a video showing the issue? Thanks in advance
> 
> When recording the entire screen. The app version is 1.4.5. Somehow, it's working now. But for some apps for example Microsoft Store it would fail and say that my current settings (60fps, 18 bitrate) are not supported for my hardware. And when it comes to recording a browser tab (YouTube) this happens..
> 
> Hope this helps!
> 
>  recordedVideo2021-03-27-202710.mp4

Actually that happens when you select a resolution higher than the one of your display. Try to set it to "set source size and resolution" and tell me if you can reproduce the issue

**Comment by binamracode** [comment]
But what about my problem?

**Comment by MarcAnt01** [comment]
@thatssotimur any update on that?
