### ISSUE TITLE
No sound recording on ARM64

### ISSUE THREAD

**Issue by eddydu44** [MarcAnt01/Fluent-Screen-Recorder#53]
Operation system : Windows 10 ARM64 build 21243.rs_prerelese.210320-1757
App Version : 1.4.5

Hello,
This app would be perfect for me but when I start a recording it does not record my system sounds.

**Comment by MarcAnt01** [comment]
Hello, internal audio recording hasn't been implemented in the stable version. Anyway I have added it to the insider version (still wip), if you want to try it, just join the Discord server :)
