### ISSUE TITLE
request: record to .gif (and/or .gifv)

### ISSUE THREAD

**Issue by firinael** [MarcAnt01/Fluent-Screen-Recorder#55]
Pretty self-explanatory request, I just want to be able to choose the output format as .gif or .gifv.

I sadly can't help with suggesting an implementation, though.

Thanks for the app by the way, it's genuinely great for someone who just wants a quick screen capture and doesn't wanna go through the bother that is OBS.

**Comment by MarcAnt01** [comment]
Hello, I don't plan to record in gif because it's a really bad format. I anyway understand that people might need it, so I'll implement the possibility to convert the video to gif once I include ffmpeg.
For reference: https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/99
