### ISSUE TITLE
Your audio does not work but your app is a 10/10

### ISSUE THREAD

**Issue by Mellomr99** [MarcAnt01/Fluent-Screen-Recorder#57]
For some odd reason audio i was using your app and I also gotta say your app is one of if not the best screen recorder apps I have to give it to you for some reason when I look back at the recording something went wrong there is no audio please fix this bug

**Comment by MarcAnt01** [comment]
We have clarified with @Mellomr99 on Discord. For someone else who might be reading, the audio is implemented in the beta. If you want to gain access to it, just join Fluent Screen Recorder Discord server and/or UWP Community Discord server and ask for the role
