### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Huzaifabee** [MarcAnt01/Fluent-Screen-Recorder#58]
I cant hear sound in fluent recorder when recording class google meet,I dont know that video has a format issue or it does not record sound.
It would be very helpful that fluent recorder records the sound of ours and pc,

**Comment by Huzaifabee** [comment]
One more issue is that this recorder has very much whitness ,when I record something it does not loook good with the result of too much brightness .

**Comment by MarcAnt01** [comment]
@Huzaifabee atm Fluent Screen Recorder doesn't record internal audio, if you really need this feature you might consider trying out the beta version that currently supports internal audio recording.
If you're wishing to do it, just join Fluent Screen Recorder Discord server or UWP Community, specifying that you want to try the beta. I'm sorry for the inconvenience, but I am working on a major update, that's still not ready to be pushed to everyone

**Comment by MarcAnt01** [comment]
> One more issue is that this recorder has very much whitness ,when I record something it does not loook good with the result of too much brightness .

Could you explain this issue? First time I hear about something similar

**Comment by MarcAnt01** [comment]
Closed the issue, feel free to open a new issue explaining the problem you're experiencing
