### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by sq4cvh** [MarcAnt01/Fluent-Screen-Recorder#65]
App not record audio from web pages

**Comment by MarcAnt01** [comment]
Hi, audio recording isn't implemented in the stable version, it's currently in the beta one, but it'll come in some weeks to the stable version 😄

**Comment by AqilCont** [comment]
Please make it soon! I really want actual audio with the recording :<

**Comment by MarcAnt01** [comment]
@AqilCont you can join the Discord server and get in touch with me, I could give you early access

**Comment by MarcAnt01** [comment]
@sq4cvh the version with audio recording is now available to everyone. Closing this.
