### ISSUE TITLE
Crash when audio recording is enabled and any Spatial sound format in windows is also enabled 

### ISSUE THREAD

**Issue by abhidan2** [MarcAnt01/Fluent-Screen-Recorder#67]
Windows Sonic for headphones, Dolby Atmos for Headphones or any other Spatial sound format combined with audio recording feature causes the app to crash immediately after start recording. When Spatial sound format is set to Off, app works fine.

**Comment by MarcAnt01** [comment]
This is really complex to record, from the next release when you record with it enabled, the app won't capture internal audio even if the toggle is on. In the future, if I find a way, I may handle it in the correct way.
