### ISSUE TITLE
open videos in a preview video player /editor and allow to save from there

### ISSUE THREAD

**Issue by FireCubeStudios** [MarcAnt01/Fluent-Screen-Recorder#7]

**Comment by MarcAnt01** [comment]
That's a good idea, are you planning to work on that soon?

**Comment by MarcAnt01** [comment]
Anyway, I would prefer to have it in another window, like Unigram (even if it's not the default option)

**Comment by MarcAnt01** [comment]
Your thoughts?
![image](https://user-images.githubusercontent.com/43090263/88777734-d9051300-d187-11ea-937e-092afe56f017.png)

**Comment by FireCubeStudios** [comment]
yes
open it in new appwindow in a mediaplayerlement
