### ISSUE TITLE
Why aren't you giving .msixbundle in releases section of GitHub for new releases?

### ISSUE THREAD

**Issue by clicky6** [MarcAnt01/Fluent-Screen-Recorder#77]
Why aren't you giving .msixbundle version of app in releases section of GitHub for new releases?

**Comment by MarcAnt01** [comment]
I stopped uploading the files, because the app is available in the Microsoft Store. Is there a specific reason why you need .msixbundle?

**Comment by clicky6** [comment]
I have blocked Microsoft Servers from firewall app so I need the .msixbundle so that install can be performed without using Microsoft Store.

**Comment by MarcAnt01** [comment]
There's [this site](https://store.rg-adguard.net/), I don't know if you already know about it, that allows you to get the .msixbundle of the latest store version just pasting the store url of the app (just google Fluent Screen Recorder Microsoft store and you'll get it). For the future I could post major updates in the releases section if you prefer anyway

**Comment by clicky6** [comment]
Yes It would be much handy if you provide .msixbundle file in releases section instead of downloading from some website or so because if we download the app from the website authenticity of the app cannot be guaranteed.

**Comment by clicky6** [comment]
Just provide .msixbundle file for stable releases that's it.
Thank You

**Comment by MarcAnt01** [comment]
@clicky6 I will from now, but take into account that .msixbundle files are really safe. You cannot install normally a non-signed packaged. The site I have provided just downloads the app from Microsoft store servers and allows you to install it manually. If you open the .msixbundle file, the pop-up in the screenshot would appear, showing you that it's a genuine app
![image](https://user-images.githubusercontent.com/43090263/132726480-34e676b6-3a5a-4a53-a054-66e44057d958.png)

**Comment by clicky6** [comment]
> @clicky6 I will from now, but take into account that .msixbundle files are really safe. You cannot install normally a non-signed packaged. The site I have provided just downloads the app from Microsoft store servers and allows you to install it manually. If you open the .msixbundle file, the pop-up in the screenshot would appear, showing you that it's a genuine app
> ![image](https://user-images.githubusercontent.com/43090263/132726480-34e676b6-3a5a-4a53-a054-66e44057d958.png)

Ok sir But the website is somewhat complex also so...

**Comment by clicky6** [comment]
I just installed and ran 1.2.0 because that was the latest release with .msixbundle file given, But the app is not opening? Why so?

**Comment by MarcAnt01** [comment]
> I just installed and ran 1.2.0 because that was the latest release with .msixbundle file given, But the app is not opening? Why so?

Probably, I bug that was fixed along the way. I'll publish a 2.0 msixbundle file soon

**Comment by clicky6** [comment]
**Thank You very much sir.**

**Comment by MarcAnt01** [comment]
Done

**Comment by clicky6** [comment]
Great.
