### ISSUE TITLE
audio is not work

### ISSUE THREAD

**Issue by babakmdi** [MarcAnt01/Fluent-Screen-Recorder#81]
i get Access is denied here

![image](https://user-images.githubusercontent.com/65450661/133887893-b5037085-e28a-45de-bdd5-4c9033d4fe12.png)

**Comment by MarcAnt01** [comment]
Hello, the internal audio recording feature is not open source and cannot be used out of Fluent Screen Recorder package

**Comment by babakmdi** [comment]
I need it . how in the world can i have it ????

**Comment by MarcAnt01** [comment]
As the license states, the code in the repo is provided "as is", the internal audio recording code is private and not for my choice. Try to reach out to me on Discord and explain the reasons why you need it and I'll connect you to the author of the library.
