### ISSUE TITLE
Crash at start-up

### ISSUE THREAD

**Issue by senolfndk** [MarcAnt01/Fluent-Screen-Recorder#86]
crashing

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2021-10-08 201653](https://user-images.githubusercontent.com/52818836/136597113-b4f2491d-b223-4f7f-93d6-ebf069aca8e0.png)

**Comment by MarcAnt01** [comment]
Hello, I have probably fixed it, but I need some testers to ensure it's working properly. In case you are interested, I published a test package here:
https://discord.com/channels/754661717052620800/754661717052620804/916819108941660170

**Comment by MarcAnt01** [comment]
This should be fixed in 2.1, let me know if you still experience crashes
