### ISSUE TITLE
Fluent Screen Recorder not working correctly when minimized

### ISSUE THREAD

**Issue by m98770** [MarcAnt01/Fluent-Screen-Recorder#9]
Using ShareX : 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/68843202/88926206-7307b100-d297-11ea-8f4c-87f60ed4c2b1.gif)

Using Fluent Screen Recorder in minimized (using Share your Display option) : 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/68843202/88926919-7a7b8a00-d298-11ea-8b03-ec8627058e98.gif)
as you can see, right after  I minimized the app , it straightly jumps to file explorer and hangs there forever, without showing desktop , desktop context menus, start screen , and lastly file explorer context menus.   All of this works correctly similar to ShareX video when I do not minimize the uwp app.

**Comment by m98770** [comment]
@MarcAnt01 Maybe you shouldn't use Suspend/Resume code at all. I guess the app suspends when minimized so this happens

**Comment by m98770** [comment]
@MarcAnt01  I strongly believe this issue is happening for suspended/resumed state of the app ![FR8Giyx8e8-output](https://user-images.githubusercontent.com/68843202/88960035-b7f60c80-d2c4-11ea-886d-c827cba65ebf.gif)..

**Comment by FireCubeStudios** [comment]
use extended execution to bypass that https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-minimized-with-extended-execution
