### ISSUE TITLE
Immediately crash when start recording 

### ISSUE THREAD

**Issue by steam3d** [MarcAnt01/Fluent-Screen-Recorder#92]
The app immediately crash when start recording on windows 11.
I did not found where log files storage and i cannot provide more information.

**Comment by MarcAnt01** [comment]
Hello, does disabling audio fix the crash for you?

**Comment by steam3d** [comment]
Yes. When audio is disabled the app works as expected

**Comment by MarcAnt01** [comment]
From the next version I'll be adding a check and if the internal audio fails to be recorded, the app won't crash, but will record videos without audio

**Comment by MarcAnt01** [comment]
After some investigation, this seem to be due to the library of internal audio recording on which I haven't worked directly and the patch I made doesn't seem to be enough

**Comment by MarcAnt01** [comment]
Hello, I have probably fixed it, but I need some testers to ensure it's working properly. In case you are interested, I published a test package here:
https://discord.com/channels/754661717052620800/754661717052620804/916819108941660170

**Comment by MarcAnt01** [comment]
This should be fixed in 2.1, let me know if you still experience crashes

**Comment by steam3d** [comment]
The app does not crush now.  Thx.
