### ISSUE TITLE
Crash when recording with audio

### ISSUE THREAD

**Issue by Ahmetozefe** [MarcAnt01/Fluent-Screen-Recorder#94]
Windows 11 Pro 21H2
OS build	22000.348
App info: Latest version from Microsoft Store as of 27 November 2021

Issue: The app will always crash when starting a recording with Audio Recording option enabled. It will not crash when it's disabled.

**Comment by MarcAnt01** [comment]
Hello, I have probably fixed it, but I need some testers to ensure it's working properly. In case you are interested, I published a test package here:
https://discord.com/channels/754661717052620800/754661717052620804/916819108941660170

**Comment by MarcAnt01** [comment]
This should be fixed in 2.1, let me know if you still experience crashes
