### ISSUE TITLE
App will crash immediately if I choose record

### ISSUE THREAD

**Issue by Jimmy-Blue** [MarcAnt01/Fluent-Screen-Recorder#97]
![image](https://user-images.githubusercontent.com/60958064/144429262-07696762-66cb-4ec4-84fe-0a4860d09f0b.png)
I can start the app in the normal way but after hitting Record, it just crash. Have reinstalled many times but so far, failed.

**Comment by MarcAnt01** [comment]
Hello, I have probably fixed it, but I need some testers to ensure it's working properly. In case you are interested, I published a test package here:
https://discord.com/channels/754661717052620800/754661717052620804/916819108941660170

**Comment by Jimmy-Blue** [comment]
@MarcAnt01 Can you send the direct link in here? Apparently, I don't have Discord, so I can't access the link you sent. Thank you.

**Comment by MarcAnt01** [comment]
@Jimmy-Blue here's the dropbox folder with the package + instructions to install
https://www.dropbox.com/sh/ncybf0dfqpkycq0/AAA-icll2_smoeekraWQYMG1a?dl=0

**Comment by Jimmy-Blue** [comment]
@MarcAnt01 I tested the beta package and there is a problem with audio recording. It is about the delay. Sometimes, the audio records faster than the actual rate of the video.

**Comment by MarcAnt01** [comment]
This should be fixed in 2.1, let me know if you still experience crashes

**Comment by Jimmy-Blue** [comment]
@MarcAnt01 I updated the official version to v2.1.0 and seems like the problem with Audio Recording still presents in this, even though the test package that you sent earlier did work fine and good as expected..
